#!/bin/sh -e

cd debian

pkgs=$(grep-dctrl -sPackage -n -FSection libdevel control)
DEB_HOST_MULTIARCH=$(dpkg-architecture -qDEB_HOST_MULTIARCH)

for p in $pkgs; do
    includes="$includes -I $p/usr/include/$1 -I $p/usr/include/$DEB_HOST_MULTIARCH"
done

for pkg in $pkgs; do
  {
    for header in $(find "$pkg" -name "*.h"); do
        gcc -MM -MT "$pkg" -E $includes $header
    done
    printf '\t%s\n' '$(info header:Depends= \
$(foreach pkg,$(sort $(filter-out $@, \
		$(foreach dep,$^,$(firstword $(subst /, ,$(dep)))))) \
	,$(pkg) (= $${binary:Version}),))'
  } | make -Bsf - >>"$pkg.substvars"
done
